{
 "title": "Envoy Services",
 "description": "Monitoring services communicating through Envoy",
 "tags": [
  "envoy",
  "monitoring"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "БД", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Сервис",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total,envoy_cluster_name)"
    }
   },
   {
    "name": "job",
    "label": "Стенд",
    "query": {
     "query": "label_values(envoy_cluster_upstream_cx_total,job)"
    }
   },
   {
    "name": "instance",
    "label": "Сервер",
    "query": {
     "query": "label_values({job=\"$job\"},instance)"
    }
   },
   {
    "name": "min",
    "label": "Grouping",
    "query": "15s, 30s, 1m, 5m, 10m, 30m, 1h, 2h, 6h, 12h"
   }
  ]
 },
 "panels": [
  {
   "title": "Состояние сервиса",
   "type": "stat",
   "description": "Shows whether the service is running; if DOWN, then at least one instance of the service is unavailable. If UNKNOWN, then there is no data.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    envoy_cluster_membership_healthy{envoy_cluster_name=\"$cluster\", job=\"$job\"}\n) == bool \nsum(\n    envoy_cluster_membership_total{envoy_cluster_name=\"$cluster\", job=\"$job\"}\n) ",
     "legendFormat": "{{hosts}}"
    }
   ]
  },
  {
   "title": "Percentage of successful service responses",
   "type": "gauge",
   "description": "A successful response is considered to be a response with the 2xx code",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(\n    sum(\n        increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\", envoy_response_code_class=~\"2\"}[$__range])\n    ) \n    /\n    sum(\n        increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\", instance=~\"$instance\",job=\"$job\"}[$__range])\n    ) * 100, \n    1\n)\n\n",
     "legendFormat": "{{instance}}/{{job}}"
    }
   ]
  },
  {
   "title": "Percentage of responses from the service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n    increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])\n) / \nsum(\n    increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])\n) * 100",
     "legendFormat": "Timeout"
    },
    {
     "expr": "sum(\n    increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\", envoy_response_code_class=~\"2\"}[$__interval])) \n/ \nsum(\n    increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])\n) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "(\nsum(\n    increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\", envoy_response_code_class=~\"5\"}[$__interval])) \n- \nsum(\n    increase(envoy_cluster_upstream_rq_timeout{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval]))\n) \n/ \nsum(\n    increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])\n)* 100",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(\n    increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\", envoy_response_code_class=~\"4\"}[$__interval])\n)\n/\nsum(\n    increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])\n) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(\n    increase(envoy_cluster_upstream_rq_xx{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\", envoy_response_code_class=~\"3\"}[$__interval])\n)\n/\nsum(\n    increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])\n) * 100",
     "legendFormat": "3хх"
    }
   ]
  },
  {
   "title": "50, 80 percentile response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "{{cluster}} 50% "
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "{{cluster}} 80%"
    }
   ]
  },
  {
   "title": "90, 99 процентиль времени ответа",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "{{cluster}} 90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=\"$cluster\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "{{cluster}} 99%"
    }
   ]
  },
  {
   "title": "RPM / Кол-во запросов в минуту",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(increase(envoy_cluster_upstream_rq_completed{envoy_cluster_name=\"$cluster\",instance=~\"$instance\",job=\"$job\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Healthcheck",
   "type": "graph",
   "description": "Each service has its own verification option. Some can be checked via tcp, others using http request to a specific endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(envoy_cluster_health_check_success{envoy_cluster_name=\"$cluster\",instance=~\"$instance\",job=\"$job\"}[$__interval])))",
     "legendFormat": "health"
    },
    {
     "expr": "round(sum(increase(envoy_cluster_health_check_failure{envoy_cluster_name=\"$cluster\",instance=~\"$instance\",job=\"$job\"}[$__interval])))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": " Number of active service hosts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_healthy{envoy_cluster_name=~\"$cluster\", instance=~\"$instance\", job=\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Number of connections to the stand",
   "type": "graph",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(envoy_http_downstream_cx_active{instance=~\"$instance\",job=\"$job\"})",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Envoy response rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(increase(envoy_listener_http_downstream_rq_xx{envoy_response_code_class=\"5\",envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) / \nsum(increase(envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) * 100",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(increase(envoy_listener_http_downstream_rq_xx{envoy_response_code_class=\"2\",envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) / \nsum(increase(envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) * 100",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(increase(envoy_listener_http_downstream_rq_xx{envoy_response_code_class=\"4\",envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) / \nsum(increase(envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) * 100",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(increase(envoy_listener_http_downstream_rq_xx{envoy_response_code_class=\"3\",envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) / \nsum(increase(envoy_listener_http_downstream_rq_completed{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) * 100",
     "legendFormat": "3хх"
    }
   ]
  },
  {
   "title": "Total number of active connections to Upstream",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(increase(envoy_cluster_upstream_cx_active{instance=~\"$instance\", job=\"$job\"}[$__interval])) by (envoy_cluster_name)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "( 50, 80, 90, 99 ) Percentile request and response times",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.8, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "80%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_http_downstream_rq_time_bucket{envoy_http_conn_manager_prefix=\"host\", instance=~\"$instance\", job=\"$job\"}[$__interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "VK API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "VK API Envoy 429",
     "type": "graph",
     "description": "Number of 429 responses from Envoy, not from Yahoo API",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "round(sum(increase(envoy_yahoo_api_rate_limit_http_local_rate_limit_enforced{instance=~\"$instance\",job=\"$job\"}[1m])))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  }
 ]
}